spring:
  data:
    mongodb:
      host: localhost
      port: 27016
      database: jwt_security
      username: manhnv2
      password: manhnv2
    redis:
      host: localhost
      port: 6379
      database: 1

application:
  security:
    jwt:
      tokenHeader: Authorization
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 30000
      refresh-token:
        expiration: 120000